// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-01-27 09:49:34

package mo.gov.safp.portal.sqlite;

import androidx.annotation.Keep;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Keep
@DatabaseTable(tableName = "UserInfo") //数据库表名，默认为类名
public class LoginResultData implements Serializable {


    /**
     * agreeTime :
     * birthday :
     * contactPhone :
     * departmentAlias :
     * departmentCode :
     * email :
     * entities : [{"address":"","code":"","commercialCode":"","contactAddress":"","contactPhone":"","dsfTaxpayerCode":"","email":"","entityType":{"code":"","namePt":"","nameZhHant":""},"govServices":[{}],"isAccountManager":"","isEntityManager":"","isServiceManager":"","namePt":"","nameZhHant":"","status":""}]
     * euid :
     * firstName :
     * gender :
     * identityIssuePlace :
     * identityNo :
     * identityType :
     * isActive : true
     * isEsignBind : true
     * isStaff : true
     * isSuperuser : true
     * loginName :
     * mobile :
     * nameCn :
     * namePt :
     * otpChannel :
     * preferredLanguage :
     * refreshToken :
     * sepbox :
     * staffcode :
     * token :
     * uid :
     * userType :
     * username :
     * verified : true
     */

    // 主键
    @DatabaseField(generatedId = true)
    public int id;
    @DatabaseField
    public String agreeTime;
    @DatabaseField
    public String birthday;
    @DatabaseField
    public String contactPhone;
    @DatabaseField
    public String departmentAlias;
    @DatabaseField
    public String departmentCode;
    @DatabaseField
    public String email;
    // 字段唯一
    @DatabaseField(unique = true)
    public String euid;
    @DatabaseField
    public String firstName;
    @DatabaseField
    public String gender;
    @DatabaseField
    public String identityIssuePlace;
    @DatabaseField
    public String identityNo;
    @DatabaseField
    public String identityType;
    @DatabaseField
    public String identityTypeDesc;
    @DatabaseField
    public boolean isActive;
    @DatabaseField
    public boolean isEsignBind;
    @DatabaseField
    public boolean isStaff;
    @DatabaseField
    public boolean isSuperuser;
    @DatabaseField
    public String loginName;
    @DatabaseField
    public String mobile;
    @DatabaseField
    public String nameCn;
    @DatabaseField
    public String namePt;
    @DatabaseField
    public String otpChannel;
    @DatabaseField
    public String preferredLanguage;
    @DatabaseField
    public String refreshToken;
    @DatabaseField
    public String sepbox;
    @DatabaseField
    public String staffcode;
    @DatabaseField
    public String token;
    @DatabaseField
    public String uid;
    @DatabaseField
    public String userType;
    @DatabaseField
    public String username;
    @DatabaseField
    public boolean verified;
    @DatabaseField
    public boolean isGxAccount;
    @DatabaseField
    public String homeAddress;
    @DatabaseField(dataType = DataType.SERIALIZABLE)
    public ArrayList<EntitiesBean> entities;
    @DatabaseField
    public String accountType;
    @DatabaseField
    public String avatar; //头像(本地暂不存)
    @DatabaseField(defaultValue = "false")
    public boolean isChild; //是子账号
    @DatabaseField(defaultValue = "false")
    public boolean isCurrent; //当前正登录的用户


    public static class EntitiesBean implements Serializable {
        /**
         * address :
         * code :
         * commercialCode :
         * contactAddress :
         * contactPhone :
         * dsfTaxpayerCode :
         * email :
         * entityType : {"code":"","namePt":"","nameZhHant":""}
         * govServices : [{}]
         * isAccountManager :
         * isEntityManager :
         * isServiceManager :
         * namePt :
         * nameZhHant :
         * status :
         */

        public String address;
        public String code;
        public String commercialCode;
        public String contactAddress;
        public String contactPhone;
        public String dsfTaxpayerCode;
        public String email;
        public EntityTypeBean entityType;
        public String isAccountManager;
        public String isEntityManager;
        public String isServiceManager;
        public String namePt;
        public String nameZhHant;
        public String status;
        public List<GovServicesBean> govServices;

        public EntitiesBean() {
        }

        @Override
        public String toString() {
            return "EntitiesBean{" +
                    "address='" + address + '\'' +
                    ", code='" + code + '\'' +
                    ", commercialCode='" + commercialCode + '\'' +
                    ", contactAddress='" + contactAddress + '\'' +
                    ", contactPhone='" + contactPhone + '\'' +
                    ", dsfTaxpayerCode='" + dsfTaxpayerCode + '\'' +
                    ", email='" + email + '\'' +
                    ", entityType=" + entityType +
                    ", isAccountManager='" + isAccountManager + '\'' +
                    ", isEntityManager='" + isEntityManager + '\'' +
                    ", isServiceManager='" + isServiceManager + '\'' +
                    ", namePt='" + namePt + '\'' +
                    ", nameZhHant='" + nameZhHant + '\'' +
                    ", status='" + status + '\'' +
                    ", govServices=" + govServices +
                    '}';
        }

        public static class EntityTypeBean implements Serializable {
            /**
             * code :
             * namePt :
             * nameZhHant :
             */

            private String code;
            private String namePt;
            private String nameZhHant;

        }

        public static class GovServicesBean implements Serializable {
        }
    }

    @Override
    public String toString() {
        return "LoginResultData{" +
                "id=" + id +
                ", agreeTime='" + agreeTime + '\'' +
                ", birthday='" + birthday + '\'' +
                ", contactPhone='" + contactPhone + '\'' +
                ", departmentAlias='" + departmentAlias + '\'' +
                ", departmentCode='" + departmentCode + '\'' +
                ", email='" + email + '\'' +
                ", euid='" + euid + '\'' +
                ", firstName='" + firstName + '\'' +
                ", gender='" + gender + '\'' +
                ", identityIssuePlace='" + identityIssuePlace + '\'' +
                ", identityNo='" + identityNo + '\'' +
                ", identityType='" + identityType + '\'' +
                ", identityTypeDesc='" + identityTypeDesc + '\'' +
                ", isActive=" + isActive +
                ", isEsignBind=" + isEsignBind +
                ", isStaff=" + isStaff +
                ", isSuperuser=" + isSuperuser +
                ", loginName='" + loginName + '\'' +
                ", mobile='" + mobile + '\'' +
                ", nameCn='" + nameCn + '\'' +
                ", namePt='" + namePt + '\'' +
                ", otpChannel='" + otpChannel + '\'' +
                ", preferredLanguage='" + preferredLanguage + '\'' +
                ", refreshToken='" + refreshToken + '\'' +
                ", sepbox='" + sepbox + '\'' +
                ", staffcode='" + staffcode + '\'' +
                ", token='" + token + '\'' +
                ", uid='" + uid + '\'' +
                ", userType='" + userType + '\'' +
                ", username='" + username + '\'' +
                ", verified=" + verified +
                ", isGxAccount=" + isGxAccount +
                ", homeAddress='" + homeAddress + '\'' +
                ", entities=" + entities +
                ", accountType='" + accountType + '\'' +
                ", avatar='" + avatar + '\'' +
                ", isChild=" + isChild +
                ", isCurrent=" + isCurrent +
                '}';
    }
}