package mo.gov.safp.portal.softtoken.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import mo.gov.safp.portal.softtoken.SoftToken;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig softTokenDaoConfig;

    private final SoftTokenDao softTokenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        softTokenDaoConfig = daoConfigMap.get(SoftTokenDao.class).clone();
        softTokenDaoConfig.initIdentityScope(type);

        softTokenDao = new SoftTokenDao(softTokenDaoConfig, this);

        registerDao(SoftToken.class, softTokenDao);
    }
    
    public void clear() {
        softTokenDaoConfig.clearIdentityScope();
    }

    public SoftTokenDao getSoftTokenDao() {
        return softTokenDao;
    }


}
